<table width=100% border=0>
         <tr>
            <td><img src='../imagens/logotipos/brasao2.png' alt='' width='60' height='63'></td>
            <td align=center>
                   TÍTULO1 AQUI DO RELATÓRIO<br>
                   TÍTULO2 AQUI DO RELATÓRIO<br>
                   site aqui
                <font size=2>
                </font>
            </td>
            <td align=right><img src='../imagens/logotipos/brasao1.png' alt='' width='60' height='63'></td>
         </tr>
      </table>

